branch-defaults:
  master:
    environment: node-express-api
environment-defaults:
  node-express-api:
    branch: null
    repository: null
global:
  application_name: node-rest-api
  default_ec2_keyname: null
  default_platform: node.js
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
